# Generated by Django 3.2 on 2021-04-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_done', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=0, null=True, verbose_name='Done')),
                ('when_done', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Habit Analytics',
            },
        ),
        migrations.CreateModel(
            name='HabitFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Habit Frequencies',
            },
        ),
        migrations.CreateModel(
            name='HabitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('reminder_question', models.CharField(max_length=250)),
                ('start_habit', models.DateTimeField()),
                ('end_habit', models.DateTimeField()),
                ('creation_day', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
            options={
                'verbose_name_plural': 'Habit Tracker',
            },
        ),
    ]
