# Generated by Django 3.2 on 2021-04-28 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittracker',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habittracker',
            name='f_repeat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.habitfrequency'),
        ),
        migrations.AddField(
            model_name='habitanalytics',
            name='done_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habitanalytics',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.habittracker'),
        ),
    ]
