# Generated by Django 3.2 on 2021-04-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_habitanalytics_when_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitanalytics',
            name='when_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
