# Generated by Django 3.2 on 2021-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_habitanalytics_when_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitanalytics',
            name='when_done',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
